# Generated by Django 3.1.5 on 2021-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[(None, '------------------------------'), ('грн.', 'UAH'), ('долл.', 'USD'), ('ев.', 'EUR')], max_length=8, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='product',
            name='producer_coun',
            field=models.CharField(choices=[(None, '------------------------------'), ('UA', 'Украина'), ('RU', 'Россия'), ('PL', 'Польша'), ('BL', 'Белорусь'), ('CN', 'Китай'), ('USA', 'Америка')], max_length=24, null=True, verbose_name='Країна Виробник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Назва'),
        ),
    ]
